-- generated by database functions generator automatically
-- for mysql 
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- Following lines remove old tables from database
DROP TABLE IF EXISTS`Questions`;
DROP TABLE IF EXISTS`Locations`;
DROP TABLE IF EXISTS`Notifications`;

CREATE TABLE `Questions` (
`QuestionId` INT  NOT NULL,
`CreationTime` DATETIME  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `Questions` ADD PRIMARY KEY(`QuestionId`); 
ALTER TABLE `Questions`  MODIFY `QuestionId` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1; 

CREATE TABLE `Locations` (
`LocationId` INT  NOT NULL,
`Content` TEXT  NOT NULL,
`FirstVarient` TEXT  NOT NULL,
`SecondVarient` TEXT  NOT NULL,
`CorrectVarient` INT  NOT NULL,
`X` DOUBLE  NOT NULL,
`Y` DOUBLE  NOT NULL,
`CreationTime` DATETIME  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `Locations` ADD PRIMARY KEY(`LocationId`); 
ALTER TABLE `Locations`  MODIFY `LocationId` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1; 

CREATE TABLE `Notifications` (
`NotificationId` INT  NOT NULL,
`Title` VARCHAR(20)  NOT NULL,
`Message` TEXT  NOT NULL,
`CreationTime` DATETIME  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `Notifications` ADD PRIMARY KEY(`NotificationId`); 
ALTER TABLE `Notifications`  MODIFY `NotificationId` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1; 

